### ISSUE TITLE
Código de Conducta (CoC)

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#1]
Creo que este es un paso importante para nuestra comunidad, tener un código de conducta para asegurar el respeto y la inclusión entre todos.

Podríamos tomar códigos de conducta de otras org como base. Dejar sugerencias acá.

**Comment by stsewd** [comment]
Para quienes deseen conocer un poco background sobre la importancia de un código de conducta: https://opensource.guide/code-of-conduct/

Cómo referencia se podría tomar https://www.contributor-covenant.org/, existe una traducción en español aquí: https://www.contributor-covenant.org/es/version/1/4/code-of-conduct.html

El código de conducta de Django https://www.djangoproject.com/conduct/

**Comment by amjalca** [comment]
Como punto de partida sugiero que se puede adjuntar a nuestros comentarios tres puntos principales:
1.	Resumen
2.	Puntos positivos, beneficios, etc.
3.	Puntos negativos, perjuicios, etc. 
4.	Otras consideraciones (Extra).

Con el fin de proporcionar el tipo de información que se desea transmitir y cuando el hilo se torne extenso las personas que acceden tengan una visión más clara de la situación.

Referencia: https://eu.battle.net/es/community/conduct

Resumen:
Se detalla el comportamiento que desea la empresa en la comunidad. Donde se pone a disposición foros. 

1.  Puntos positivos
     a.	El participante debe considerar que su participación es un privilegio.
     b.	Fomenta el respeto racial, étnico, sexual y forma de comunicación.
     c. 	Control de temas propuestos e importancia en el comentario.

2.  Puntos negativos
     a.	Ejemplo de código de conducta extenso.
     b.	Hay puntos que no se alinean a Python Ecuador.

Finalmente considero que los puntos positivos pueden ser tomandos para elaborar el código que se propone.

**Comment by ovnicraft** [comment]
Dejo tambien como referencia el CoC de Python https://www.python.org/psf/codeofconduct/

**Comment by stsewd** [comment]
También creo que debemos hacer algo simple y conciso, nada muy largo ni muy estructurado.

**Comment by ragutierrez** [comment]
Esto se había trabajado en 2015.

https://github.com/miltonlab/python-ecuador-codeofconduct

**Comment by stsewd** [comment]
@ragutierrez está muy bueno, te gustaría hacer un pull request con eso? Tal vez con una mezcla de https://www.contributor-covenant.org/es/version/1/4/code-of-conduct (para cubrir ciertos puntos)

**Comment by ragutierrez** [comment]
Voy a hacer una mezcla de todo y colocarlo en https://oasis.sandstorm.io/shared/Pg23-idgN4Pp5xhOhy0GP8OIRwbS0uBGy0cs4_1rfMi

**Comment by stsewd** [comment]
@ragutierrez vi que ya tienes redactado el código de conducta, te gustaría hacer un pull requests agregándolo en https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/pages/coc.rst?
