### ISSUE TITLE
Agregar link a la web en archivo README

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#118]
Actualmente tenemos un link en la descripción del repositorio, pero también deberíamos poner un link en el README https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/README.md

Creo que un buen lugar es justo donde dice `... sitio de Python Ecuador`

**Comment by stsewd** [comment]
Arreglado en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/131

**Comment by domenicadojo** [comment]
https://onlinelibrary.wiley.com/doi/pdf/10.1002/eqe.2725

**Comment by ivanletralok** [comment]
mdfkl
