### ISSUE TITLE
AYUDA Arduino + Cpp

### ISSUE THREAD

**Issue by Veronelli** [PythonEcuador/PythonEcuador.github.io#129]
Me gustaria saber como puedo hacer un programa con c++ para arduino. Estuve investigando y me encotre con varios problemas.
Tema es que ya tengo el archivo ".h" pero no me funciona esa parte.
Programo con CodeBlocks.
¿puede ver una alternativa?
#include "SerialClass.h"
int main(){

  Serial* Arduino = new Serial("Puerto");

}

**Comment by stsewd** [comment]
Hola, este repositorio es sólo relacionado con la web de la comunidad de Python Ecuador. Podrías hacer tus preguntas en nuestro canal de telegram https://t.me/pythonecuador
