### ISSUE TITLE
Link de reportar errores no se ve en la pagina principal

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#133]
En la página principal el color del link se mezcla con el del fondo

![Screenshot_2019-06-15 Python Ecuador](https://user-images.githubusercontent.com/4975310/59558104-fc82f380-8faf-11e9-918a-6e6e0bc41b90.png)

No estoy seguro de la mejor forma de _arreglar_ esto, sugerencias bienvenidas :)

el link fue agregado en #132

**Comment by Seburath** [comment]
Link en morado

**Comment by stsewd** [comment]
@Seburath no va con el estilo del resto del sitio, tal vez dejarlo en blanco como el resto del texto? (pero ponerlo subrayado)

**Comment by Seburath** [comment]
O el color que sale cuando le haces foco con el raton, ese queda bien.
