### ISSUE TITLE
Hipervinculo dañado

### ISSUE THREAD

**Issue by juanfelicc** [PythonEcuador/PythonEcuador.github.io#140]
**Descripción del error**

en la pagina de usuario al dar click en guias se devuelve a la pagina principal de phyton ecuador

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by stsewd** [comment]
Hola, podrías ser un poco más específico? Poner el link de la página donde observaste el error sería de ayuda

**Comment by juanfelicc** [comment]
![Captura](https://user-images.githubusercontent.com/51864512/60761170-a9c5b600-a008-11e9-9745-9445683929b1.PNG)
Ese link deberia enviarte a la guia de python sin embargo te devuelve a la pagina principal.

**Comment by stsewd** [comment]
El enlace es el correcto para mi

https://pythonecuador.org/guias/

El link ahí redirecciona a https://pythonecuador.org/guias/colaborar/, lo cual es correcto.

También puedo ver que tienes una versión desactualizada del sitio,
puedes actualizarlo siguiendo los pasos en https://pythonecuador.org/guias/colaborar/#mi-segundo-pull-request

**Comment by stsewd** [comment]
No puedo reproducir este bug de manera local. Puedes probar ejecutando `nikola clean` antes de ejecutar `nikola auto`?

**Comment by juanfelicc** [comment]
Ya lo pruebo
