### ISSUE TITLE
Agregar página con el zen de python

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#146]
Crear una página en `pythonecuador.org/zen` con la traducción de https://www.python.org/dev/peps/pep-0020/ y un link hacia el PEP.

También podríamos linkear a esta página desde https://pythonecuador.org/quienes-somos/ u otra página?

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by Dongor3** [comment]
Yo tomo este issue

**Comment by stsewd** [comment]
Resuelto en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/190
