### ISSUE TITLE
Re-escribir templates de mako a jinja

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#155]
Por defecto los templates usados en los temas usan mako, y personalmente encuentro que hacer templates con jinja es mucho más agradable. Nikola por defecto usa mako, pero hay una guía en la web de nikola de como usar jinja. La verdad no es que tengamos muchos templates, así que la migración debería ser "pequeña"

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by stsewd** [comment]
También se podría aprovechar esto para migrar a bootstrap4 #113

**Comment by Danielrick88** [comment]
Estoy interesado en hacer esta tarea. Tengo que instalar Jina2 localmente?

**Comment by stsewd** [comment]
La documentación en https://www.getnikola.com/theming.html debería tener todo lo necesario para poder realizar esta tarea. Aunque si requiere estar familiarizado con el proyecto para poder hacerla, igual nos puedes ir preguntando en las sesiones de jitsi si tienes algún problema!
