### ISSUE TITLE
Actualizar links a nuevo dominio

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#158]
Tenemos nuevo dominio python.ec, hay un par de links que aún apuntan a pythonecuador.org

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by ovnicraft** [comment]
Ahora mismo da 404 :(

**Comment by stsewd** [comment]
Arreglado en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/181
