### ISSUE TITLE
Fijar navbar del sitio (Recomendación para mejora) 

### ISSUE THREAD

**Issue by rpalaciosg** [PythonEcuador/PythonEcuador.github.io#166]
# Fijar navbar del sitio

Hola amigos, la idea es dejar fija el `navbar` del sitio miestras se navega verticalmente en cualquier página del mismo; sobre todo aquiellas con mucho contenido por ejemplo `https://python.ec/guias/colaborar/` de las guías. Esto con el objetivo de facilitar la navegación y tener a mano siempre los menús e información a la que el usuario puede acceder en el sitio.

## Cambios de diseño
Este cambio no implicá ninguna diferencia tan evidente, simplemente que se verá siempre el navbar sobre cualquier  contenido.

## Pruebas
**Sin `navbar` fija:**

![navbar_no-fija](https://user-images.githubusercontent.com/11642622/62071999-51e32f00-b203-11e9-8f57-722a0899403b.gif)

**Con `navbar` fija**

![navbar-fija](https://user-images.githubusercontent.com/11642622/62072375-21e85b80-b204-11e9-89fa-6658dbcadd25.gif)

**Comment by stsewd** [comment]
No estoy seguro si es de beneficio. Las secciones del navbar actual no requieren de atención del usuario mientras se navega. Preferiría fijar la tabla de contenidos de la página actual (como sidebar) en lugar del navbar.

Alguien tiene otra opinión? /cc @Seburath

**Comment by rpalaciosg** [comment]
> No estoy seguro si es de beneficio. Las secciones del navbar actual no requieren de atención del usuario mientras se navega.
Bueno es verdad puede ser que si implique solo en el diseño, ya que de gustos y colores hay muchos. 😄  Pero en este caso y en mi opinión, creo puede servir más para los recien llegados, en cosas como: 
- para hacerles saber que están en el sitio de 'Python Ecuador', en caso de tener muchas pestañas abiertas,etc
- que pueda conocer en resumen o de un vistazo rápido , la información que puede tener a mano de la comunidad solo viendo el navbar.

Pero bueno se que eso de si servirá o no servira puede ser relativo, pero no se que piensen los demás.

> Preferiría fijar la tabla de contenidos de la página actual (como sidebar) en lugar del navbar. 
La posibilidad de esta idea me parece muy buena  e interesante, seria beneficioso fijar el contenido como sidebar al momento de leer las guias sobre todo, y ayudaría a los usuarios a ubicarse o saber en que parte del contenido se encuentran, tipo un minimapa.

Y muchas gracias por las opiniones.
