### ISSUE TITLE
Actualizar etiquetas

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#167]
Nuevas etiquetas han sido agregadas y otras eliminadas, hay que actualizarlas aquí https://python.ec/guias/colaborar/#buscando-tareas

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by renatojobal** [comment]
Me gustaría poder aportar trabajando en este issue
