### ISSUE TITLE
Agregar más images a la guía de colaborar

### ISSUE THREAD

**Issue by stsewd** [pythonecuador/pythonecuador.github.io#168]
Hay partes que podrían tener imágenes para ilustrar mejor los pasos. Por ejemplo en https://python.ec/guias/colaborar/#realizando-cambios 

> Dirígete a la página del proyecto y verás un mensaje sugiriéndote hacer un pull request (PR). En la descripción del PR describe brevemente los cambios que hiciste.

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by enri-nun** [comment]
voy añadir imágenes en la sección de **Mi segundo Pull Request**

**Comment by stsewd** [comment]
Nos faltan más imagenes aún :)

**Comment by daniel0ar** [comment]
Voy a actualizar las imágenes con el nuevo nombre del repositorio en minúsculas "pythonecuador.github.io" (no funcionan los comandos de Git con el nombre en mayúscula "Pythonecuador.github.io") y agregar las imágenes para hacer Pull Requests.
