### ISSUE TITLE
Agregar página de 404

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#169]
GitHub pages sirve el archivo `404.html` si hay un 404. Para ello se debe crear el archivo `pages/404.rst`. El contenido debe ser con algo de humor :snake: 

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by stsewd** [comment]
Una idea que surgió fue poner el juego de snake :)

Podríamos usar este :)

https://gist.github.com/straker/ff00b4b49669ad3dec890306d348adc4

**Comment by Seburath** [comment]
Cuando creo el pages/404.rst no me funciona el mensaje de 404 para cualquier pagina, veo que se va a 404/index.html
No encuentro nada de esto en la documentacion de Nikola, donde puedo ver un ejemplo?

**Comment by Seburath** [comment]
tal vez usar esto?
https://plugins.getnikola.com/v7/errorpages/

**Comment by stsewd** [comment]
@Seburath puedes ver un ejemplo aquí https://github.com/stsewd/stsewd.github.io/blob/src/pages/404.rst

**Comment by Seburath** [comment]
jajaja que excelente! gracias

**Comment by Seburath** [comment]
![image](https://user-images.githubusercontent.com/22159934/62825091-ecc8fb00-bb6b-11e9-98a1-0ba034538fff.png)

![image](https://user-images.githubusercontent.com/22159934/62825096-036f5200-bb6c-11e9-9f90-a3aa24d6ef5a.png)
Ok, esto es lo que me pasaba, funciona en /404.html pero no funciona cuando el error 404 ocurre, que estoy haciendo mal?

**Comment by stsewd** [comment]
@Seburath nikola no sirve páginas `404`, eso es una configuración en el servidor. GitHub pages tiene esa configuración

**Comment by Seburath** [comment]
entendí, me estaba ahogando en un vaso de agua... jajaja
