### ISSUE TITLE
Ignorar otros directorios en git

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#17]
Existen algunos archivos y directorios que no están incluidos en el gitignore del proyecto. Estos archivos y directorios son autogenerados o no forman parte del proyecto en si, encuéntralos y actualiza el gitignore :)

Por ejemplo, al crear un ambiente virtual se crea un directorio `venv/`, este no es parte del proyecto y debe ser agregado al gitignore https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/.gitignore.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by rpalaciosg** [comment]
Estoy trabajando en esta tarea.
