### ISSUE TITLE
Acomodar Footer 

### ISSUE THREAD

**Issue by Seburath** [PythonEcuador/PythonEcuador.github.io#176]
Creo que se ve muy grande para footer, el diseño esta chevere, tal vez acomodarlo un poco mas.
En una pantalla grande el footer aparece en el medio.

**Comment by stsewd** [comment]
Podrías ser más específico del cambio a hacer?

![Screenshot_2019-10-20 Becas Python Ecuador](https://user-images.githubusercontent.com/4975310/67163292-cd500a80-f332-11e9-8324-6ae71f37a25f.png)

Tal vez los íconos menos grande, o usar íconos pequeños + texto?

**Comment by Seburath** [comment]
Comunidad Python Ecuador © 2019 Todos los derechos reservados.
 en una sola linea y que este apegado a la parte inferior de la pantalla.

**Comment by Seburath** [comment]
El diseño quedo muy bien, solo es una idea para acomodarlo a que se vea mejor :)

**Comment by Seburath** [comment]
En una pantalla mas grande el footer aparece en el medio.

**Comment by Seburath** [comment]
![image](https://user-images.githubusercontent.com/22159934/80275696-9aebe500-86a8-11ea-867e-52be54e42bf0.png)

**Comment by Seburath** [comment]
Se veria mejor si el footer quedara pegado abajo.

**Comment by stsewd** [comment]
@Seburath no en monitores grandes

**Comment by Seburath** [comment]
ohhh entiendo, ok, creo que solo era una preferencia personal jajaja
