### ISSUE TITLE
SqlTableDependency se instalo pero no me aparece en las referecias 

### ISSUE THREAD

**Issue by edua9920** [PythonEcuador/PythonEcuador.github.io#179]
Buenas y espero que me puedan ayudar

Estoy elaborando un proyecto en C#
tengo un error de referencia con SqlTableDependency se me instala correctamente pero no me aparece  en las referencia de mi proyecto y eso me causa un error:

Aqui me dice que se instalo correctamente:
![Captura](https://user-images.githubusercontent.com/58120138/69487464-bb312280-0e30-11ea-91bb-d6ae39f6547a.JPG)

Pero en las referencias de mi proyecto no me aparece:
![Captura2](https://user-images.githubusercontent.com/58120138/69487474-ddc33b80-0e30-11ea-8894-70e97f377ba4.JPG)

Lo cual me causa el siente error;
![Captura1](https://user-images.githubusercontent.com/58120138/69487481-08ad8f80-0e31-11ea-972c-35514ebd5db6.JPG)

![Captura3](https://user-images.githubusercontent.com/58120138/69487533-039d1000-0e32-11ea-9808-845e9f6c6e75.JPG)

 ---

Espero me puedan ayudar

**Comment by stsewd** [comment]
Hola @edua9920, este repositorio es para tratar temas relacionados con el desarrollo de la web de la comunidad de Python Ecuador.

No conozco de c# (nuestra comunidad es más orientada a python), pero podrías probar preguntando de nuestro canal de telegram https://t.me/pythonecuador

**Comment by edua9920** [comment]
Ok muchas gracias:
