### ISSUE TITLE
Recomendar herramienta para chequear ortografía

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#18]
El español es un poco complicado con muchas reglas, así que es muy fácil de cometer ciertos horrores o que se nos pase una palabra mal escrita. Sería bueno recomendar alguna herramienta para chequear esto por nosotros. Languagetool es open source y funciona desde el navegador https://languagetool.org/, podríamos poner esta información en la sección de colaborar, debe hacerce después que se mezcle https://github.com/PythonEcuador/PythonEcuador.github.io/pull/15

**Comment by richiprieto** [comment]
herrores? jajaja

**Comment by stsewd** [comment]
Era horrores :p

**Comment by Seburath** [comment]
yo lo hago, como quien aprendo a usarlo... jajaja

**Comment by stsewd** [comment]
Implementado en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/245
