### ISSUE TITLE
Actualizar template de email para incluir link a la web de pyec

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#188]
En esta página https://python.ec/guias/licencias/ hay un template de ejemplo, estaría bueno poner el link a https://python.ec/ al final. Algo así como "Conoce más sobre la comunidad en https://python.ec/"

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by hugofer93** [comment]
este issue debe cerrarse, ya se hizo el merge https://github.com/PythonEcuador/PythonEcuador.github.io/pull/189 al repo.
