### ISSUE TITLE
Tecnologías a usar

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#2]
Una desición importante, la idea es crear un blog estático simple con un landing page y unas cuatro secciones con información sobre la comunidad.

GitHub tiene soporte directo con [Jekiyll](https://jekyllrb.com/) y en el mundo de Python tenemos varias opciones interesantes, la que he estado revisando es [nikola](https://getnikola.com/)

Sus sugerencias y experiencias son importantes para decidir.

**Comment by codeadict** [comment]
**http://getpelican.com** es la opcion mas popular en el mundo Python, yo lo he usado y funciona perfecto con GutHub Pages.

**Comment by codeadict** [comment]
Por otro lado en velocidad de compilacion y facilidad de usar https://gohugo.io es genial pero esta en Golang , no Python.

**Comment by ovnicraft** [comment]
A la final lo que va a github pages es statics, me gusta muchisimo gohugo sin embargo podré aportar poco ya que no soy frontend.

**Comment by stsewd** [comment]
Creo que la opción más favorable estaría mantenerse en el ambiente de python, así es más fácil buscar gente que colabore (aunque ahora mismo no están presentes :cry:)

**Comment by arkhan** [comment]
nikola +1, o si se quiere hacer algo mas from scratch podria ser django o flask....

**Comment by dabada83** [comment]
también apoyo el uso de nikola

**Comment by ovnicraft** [comment]
Podemos definir un deadline para la generación de los staticos ?

**Comment by stsewd** [comment]
@ovnicraft estaba pensando lo mismo, creo que la decisión está entre nikola y pelican. Si se arma una encuesta? (creo que sería más rápido).

La semana más que propones es para elegir el generador estático o también la plantilla/tema?

**Comment by Neogeoakb** [comment]
Me gustaría que utilicen Pelican, hay varios temas en github que pueden servir de plantillas para la página: http://www.pelicanthemes.com/.

**Comment by ovnicraft** [comment]
@stsewd somos pocos, los que hemos votados aca esta puesto, podemos en base a esto decidir y proceder; no demorarnos mucho en algo simple.

**Comment by stsewd** [comment]
@ovnicraft Totalmente de acuerdo, el sábado podríamos contar los votos para tomar la decisión.

**Comment by codeadict** [comment]
Cualquier cosa funciona, lo importante es que haya comunidad, el website es trivial. Donde yo vivo comenzamos la comunidad Python sin website y usamos Meetup, al final lo que importa es reunirse, compartir experiencias. Aqui les dejor para referencia https://www.meetup.com/Saint-Petersburg-Python-Meetup/

**Comment by codeadict** [comment]
Probablemente @kabala puede ayudar con lo del FE bien rapido, el hizo el logo y tambien puede hacer JS/HTML/JS muy bien

**Comment by stsewd** [comment]
@codeadict gracias por las sugerencias! Ya tenemos página de meetup https://www.meetup.com/es/python-ecuador, el objetivo del website es tener toda la información de la comunidad en un sólo lugar (con quién contactarse si se quiere armar un evento, cosas así). Y también el otro objetivo es hacer que la comunidad participe, cosa que no creo estar logrando hasta ahora :stuck_out_tongue_closed_eyes:

**Comment by stsewd** [comment]
De lo que pude leer rápidamente estamos así:

Nikola: 3
Pelican: 2

A alguien le interesa hacer el primer PR con el setup inicial?

**Comment by stsewd** [comment]
Cerrado en #3
