### ISSUE TITLE
Sección de reglas

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#20]
Esta sección necesita ser completada.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by vek88** [comment]
Voy  a trabajar en esta sección.

**Comment by stsewd** [comment]
Esta sección fue mezclada con el código de conducta https://github.com/PythonEcuador/PythonEcuador.github.io/pull/117
