### ISSUE TITLE
Agregar issue template para actualizar partes de la guía/web

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#214]
Cuando queremos abrir un issue https://github.com/PythonEcuador/PythonEcuador.github.io/issues/new/choose tenemos dos opciones, bug y feature, pero muchas veces sólo queremos mencionar que falta actualizar algún parrafo, agregar documentación, etc. Debemos tener un template para esos casos.

https://github.com/PythonEcuador/PythonEcuador.github.io/tree/src/.github/ISSUE_TEMPLATE

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by y-martinez** [comment]
Hola buenas noches, puedo trabajar en este issue?

**Comment by stsewd** [comment]
@y-martinez claro que si! También te puedes unir a nuestro evento de hacktoberfest donde te podemos ayudar https://python.ec/hacktoberfest/
