### ISSUE TITLE
Separar las "Sesiones" del calendario

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#217]
El calendario de eventos podría ser más general y mostrar todos los eventos de la comunidad, no sólo las sesiones https://python.ec/calendar/ Deberíamos tener una nueva página explicando lo que hacemos en las sesiones.

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by Seburath** [comment]
Resuelto en #241
