### ISSUE TITLE
Agregar hacktoberfest a la lista de eventos

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#218]
En https://python.ec/eventos/ deberíamos listar el hacktober fest, y ampliar un poco más esta página para que cada tipo de eventos tengan una descripción.

---

Si estás interesada/o en hacer esta tarea, coméntalo, así otras personas lo saben.
¿Tienes dudas? pregúntanos en [telegram](https://t.me/pythonecuador) o en este issue.

**Comment by csampedroc** [comment]
Hola, como están? puedo trabajar en este issue ?

**Comment by stsewd** [comment]
@csampedroc hola, claro que si! Si necesitas ayuda, el día de mañana te puedes conectar en nuestras salas de element https://python.ec/hacktoberfest/#plataforma

**Comment by csampedroc** [comment]
Genial @stsewd estoy trabajando ya en ello.

**Comment by Seburath** [comment]
Dale cuando puedas te unes a la llamada, para estar conversando! ;)

**Comment by Seburath** [comment]
Resuelto en #252
