### ISSUE TITLE
Sección "Quienes somos"

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#22]
Esta sección necesita ser completada

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by gomezgleonardob** [comment]
Yo voy a trabajar en esta tarea

**Comment by stsewd** [comment]
@ZolMaria 

Creo que sería algo así...

- ¿Quienes somos? (Filosofía y metas)

Un grupo de entusiastas que busca promover el software libre, descentralizar el conocimiento, etc a través de Python.

-  ¿En que ciudades estamos?

En todo el Ecuador p:

-  ¿Por qué lo hacemos?

Por que nos apasiona, queremos un mundo donde el conocimiento sea libre y no exista ningún tipo de barrera para aprender.

-  ¿Quienes se pueden unir?

Te gusta aprender y compartir? Ya estás dentro!

---

Algo más o menos así o ahí le puedes redactar algo mucho mejor!

**Comment by stsewd** [comment]
Esto fue resuelto en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/62
