### ISSUE TITLE
Logo de Python Ecuador

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#24]
El archivo original del logo no lo tenemos. Si de casualidad lo tienes, puedes agregarlo en el sitio para usarlo luego, o puedes proponer la creación de otro o hacer el mismo :). El logo se lo puede poner en el directorio `files/` https://getnikola.com/handbook.html#adding-files

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by Seburath** [comment]
yo lo tengo

**Comment by stsewd** [comment]
Ya lo tenemos en https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/images/logos/python-ecuador.png
