### ISSUE TITLE
En pantallas pequeñas el logo no queda bien.

### ISSUE THREAD

**Issue by Seburath** [pythonecuador/pythonecuador.github.io#257]
![image](https://user-images.githubusercontent.com/22159934/95404480-c5d69800-08da-11eb-9b9a-9d038c864bec.png)

Esta feo que el logo se mescle con el titulo en pantallas pequeñas, cosa que no pasa si esta en una pantalla mas grande:

![image](https://user-images.githubusercontent.com/22159934/95404599-1c43d680-08db-11eb-939d-afeaec679682.png)

Si sabes CSS este es un buen Good First Issue

**Comment by stsewd** [comment]
También creo que el logo podemos bajarle la resolución (logo alternativo) para que cargue rápido en la web.

**Comment by stsewd** [comment]
El logo ya fue acomodado, sólo falta que le pongamos uno con una resolución más pequeña para que cargue rápido

**Comment by csampedroc** [comment]
Hola amigos, se ha cambiado la resolución del logo, estoy enviando el pull request

Resolución Original (236kb)
![image](https://user-images.githubusercontent.com/31772973/95783478-866fc900-0c97-11eb-9ef7-31ee9799c568.png)

Con resolución más baja (66kb)
![image](https://user-images.githubusercontent.com/31772973/95783417-65a77380-0c97-11eb-8919-f2f700c164f2.png)
