### ISSUE TITLE
Explicar el significado de cada etiqueta del repo

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#28]
Tal vez sea bueno documentar esto en la sección de `/colaborar`.

Se debe explicar el significado de las etiquetas que están en https://github.com/PythonEcuador/PythonEcuador.github.io/labels. O tal vez un link y editamos el significado de las etiqueta en GitHub.

También está bueno mencionar que si eres nuevo los issues con la etiqueta `Good First Issue` son excelentes para aportar.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by richiprieto** [comment]
Voy a trabajar en esta tarea

**Comment by stsewd** [comment]
Hecho en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/42
