### ISSUE TITLE
Mini tutorial de reStructuredText

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#29]
Para las personas que son nuevas en este lenguaje, estaría muy bueno tener una pequeña guía: cómo hacer un título, negrita, cursiva, listas, imágenes, links, etc.

Creo que esto estaría dentro de la sección colaborar.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by Wipipe** [comment]
yo estoy haciendo

**Comment by israteneda** [comment]
Estoy trabajando en este issue.

**Comment by rpalaciosg** [comment]
@stsewd Parece que otras personas están trabajando en esto, haré un PR con mi versión y podríamos comparar o unificar como quien se practica trabajar varias personas a la vez en un mismo issue.

**Comment by stsewd** [comment]
Pero no hay una PR desde hace ~3 meses, sientete libre de tomar el issue

**Comment by rpalaciosg** [comment]
Gracias.

**Comment by rpalaciosg** [comment]
Tengo una duda, se debe agregar este mini tutorial en la misma sección colaborar o crear otra sección o página y poner el link con la referencia a esa sección o página?

**Comment by stsewd** [comment]
En otra página, pero dentro de la sección de guias

**Comment by stsewd** [comment]
Parte de la guía fue agregada en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/128, podemos expandirla un poco más.

**Comment by rpalaciosg** [comment]
Hola amigos, que bien que ya hay una parte del rst, disculpas por la demora en subir algo.
Tengo algo listo también con lo que quisiera contribuir para expandir esta guía, tiene un enfoque un poquito diferente, pero se puede acoplar a lo actual. 
El tema es que está en una rama diferente. Puedo añadirlo hoy en la noche y hacer un PR para que lo revisen y vean que tal.

**Comment by stsewd** [comment]
@rpalaciosg genial!

**Comment by stsewd** [comment]
Arreglado en  https://github.com/PythonEcuador/PythonEcuador.github.io/pull/142
