### ISSUE TITLE
Cambiar tipo de archivo de imagen para mejorar el rendimiento

### ISSUE THREAD

**Issue by ghostbounty** [pythonecuador/pythonecuador.github.io#298]
Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption.

- ¿Cuál sección es? 
- Landing Page
- Motivación de lo que se puede mejorar o cambiar
- Cambiar el tipo de archivo de imagen

*Screenshot de Lighthouse
![image](https://user-images.githubusercontent.com/82419364/194718974-c1a6f805-99de-461b-80e0-b65f0adf791a.png)

**Comment by stsewd** [comment]
Esto fue resuelto en https://github.com/pythonecuador/pythonecuador.github.io/pull/301
