### ISSUE TITLE
Actualizar enlace en README

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#48]
¡Ya tenemos dominio! https://pythonecuador.org/

El readme está con el viejo dominio (pythonecuador.github.io) https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/README.md. Deberíamos cambiarlo.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by stsewd** [comment]
@rpalaciosg claro que si!

**Comment by stsewd** [comment]
Puedes seguir la guía para colaborar en https://pythonecuador.org/guias/colaborar/, si tienes alguna pregunta o duda nos preguntas en telgram o aquí :)

**Comment by rpalaciosg** [comment]
@stsewd Hola, tengo una consulta, sengún el issue #48 debo cambiar el dominio de "pythonecuador.github.io" anterior a "pythonecuador.org", es correcto?

En caso de ser correcto, estoy tratando de hacer push al fork que realice con la modificación, pero al hacer git push -u origin me sale un error fatal :face_with_head_bandage: "fatal: The current branch arregla-issue-48 has no upstream branch.
To push the current branch and set the remote as upstream, use", buscando un poco dice que es porque clone el repositorio con https y mi contraseña no puede estar funcionando, aun no logro encontrar el problema, alguna sugerencia?
Gracias.

**Comment by stsewd** [comment]
@rpalaciosg hola, es un pequeño error del tutorial, al parecer ese comando no funciona en todas las versiones de git, luego lo corregiré. Prueba con el comando `git push -u origin arregla-issue-48`

**Comment by rpalaciosg** [comment]
Muchas gracias @stsewd. Ya pude hacer el push y el pull request, espero este correcto. Una duda que tengo es, en el archivo README.md hay un enlace de travis-ci, y en una parte tiene "PythonEcuador.github.io"

**Comment by stsewd** [comment]
Ese link se refiere a que debe apuntar a este repositorio. `PythonEcuador.github.io` en esa parte se refiere al nombre de este repo, el cual coincide con el viejo dominio. Es decir, en esa parte es correcto :)
