### ISSUE TITLE
Indicar pasos para configurar git

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#49]
En nuestra guía de colaboración https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/pages/guias/colaborar.rst no están los pasos para configurar git `git config --global user.name "Juan Perez"` y `git config --global user.email "juan@perez.com"`. Deberíamos agregarlos en esta sección https://pythonecuador.org/guias/colaborar/#realizando-cambios, así las personas que son nuevas en git pueden hacer cambios sin problemas. El objetivo no es hacer un tutorial de git (por si acaso).

**Comment by rpalaciosg** [comment]
¿Este issue trata sobre hacer una guía de como configurar Git por primera vez?

**Comment by stsewd** [comment]
@rpalaciosg si!, aunque no necesarimente una guía completa, sólo indicando esos dos comandos :)

**Comment by stsewd** [comment]
Por cierto, actualicé la guía con pasos para hacer un segundo pull requests https://pythonecuador.org/guias/colaborar/#mi-segundo-pull-request Me dices si algo no está claro

**Comment by rpalaciosg** [comment]
ok, puedo trabajar en esto?

**Comment by stsewd** [comment]
Ese directorio debe ser ignorado (hay una tarea creada para ello https://github.com/PythonEcuador/PythonEcuador.github.io/issues/17)

**Comment by stsewd** [comment]
Resuelto en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/56
