### ISSUE TITLE
Favicon de Python Ecuador

### ISSUE THREAD

**Issue by Scoowy** [PythonEcuador/PythonEcuador.github.io#53]
Revisando la página web, note que faltaba algo, que personalmente creo que es importante visualmente hablando y es el _favicon_ de la página, por este motivo decidí crear este `issue`.
Por lo personal pienso que un _favicon_ le da un toque más profesional y único al sitio web.

**Comment by stsewd** [comment]
Si!, cuando tengamos el logo podríamos agregarlo https://github.com/PythonEcuador/PythonEcuador.github.io/issues/24

**Comment by Scoowy** [comment]
Disculpen, pensé que ese tema ya había sido resuelto.
Entonces lo dejamos en pendiente asta determinar el logo #24

**Comment by Scoowy** [comment]
Bueno, me alegro entonces haberlo hecho como primer aporte a esta comunidad.

**Comment by stsewd** [comment]
Resuelto en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/57
