### ISSUE TITLE
Poner tiempo límite para contribuciones

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#55]
Pronto nos vamos a ir quedando sin issues que no estén "ya tomados", pero algunos que han sido tomados no muestran actividad de estar siendo resueltos. Estaría bueno que las personas que tienen ganas de contribuir puedan tomar la tarea si la persona que dijo que lo iba a hacer no muestra actividad en 3 semanas (o menos?). Esto iría en la guía de colaborar https://github.com/PythonEcuador/PythonEcuador.github.io/blob/src/pages/guias/colaborar.rst

**Comment by daniel19899** [comment]
lo voy hacer yo

**Comment by stsewd** [comment]
Resuelto en #93
