### ISSUE TITLE
Documentar sobre el #PyPizza

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#6]
Si todo está saliendo bien y les gustó :) estaría bueno documentar el workflow del evento en algún lado. Cualquier persona siéntase libre de implementar esto o sugerir dónde valdría la pena ponerlo.

Se puede tomar un poco del texto del evento en meetup https://www.meetup.com/es/python-ecuador/events/250504106/

**Comment by WhiteHatTux** [comment]
Me voy a poner a escribir unas lineas sobre el PyPizza bajo la sección de Eventos.

**Comment by stsewd** [comment]
Cerrado en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/12
