### ISSUE TITLE
Encontrar forma de remover script que muestra imagenes

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#65]
Actualmente no creo que sea necesario este "feature" (cuando se da click en una imagen, esta se puede ver en grande en la misma página). Esto es un problema cuando se quiere usar una imagen con un enlace externo (el script trata de abrir este enlace como una imagen).

Esto es un problema en la página de sponsors, si no hay manera de remover selectivamente este script, hay que quitarlo de todo el sitio (creo que no es de utilidad de todos modos).

**Comment by rpalaciosg** [comment]
Hola, aun no estoy seguro, tengo que probar e investigar un poco más, pero parece que la propiedad `FEED_PREVIEWIMAGE` en la línea _1196_ en el archivo _conf.py_  nikola lo pone por defecto en **true** aun no este agregada la propiedad, lo que hace que se muestre una vista previa de las imágenes. 

![image](https://user-images.githubusercontent.com/11642622/47979375-d77ce880-e090-11e8-8bc0-4ca2ef17cbd9.png)

Para evitar esto se podría descomentar esta propiedad y asignarle falso:

```py
FEED_PREVIEWIMAGE = False
```

**Comment by stsewd** [comment]
Parece que esto se arregló cuando se actualizó la versión de nikola en #89
