### ISSUE TITLE
El contenido de la pagina no está centrado

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#68]
El contenido principal (revisar elementos con class `container`) están movidos hacia la derecha por 15px, traté de debugear un poco, pero no pude encontrar de donde viene esa regla, traté de sobreescribir la regla, pero tampoco funcionó... Mi última idea es que esta regla es sobre escrita en runtime con un script de js.

![screenshot from 2018-08-21 01-43-42](https://user-images.githubusercontent.com/4975310/44385090-fd5c0d80-a4e3-11e8-9046-c751d54d67db.png)

**Comment by rpalaciosg** [comment]
Hola amigos, estoy intentando resolver este bug, pero tengo una duda. El fork que hice la primera vez a este repositorio, ¿estará siempre actualizado con los cambios del original?, o ¿debo hacer otro fork? Hice  ```git pull``` me sale el mensaje _Already up-to-date_. 
¿Puedo seguir trabajando en el repositorio local que tengo?

**Comment by rpalaciosg** [comment]
Creo que se cual es el problema, la clase no es `container` sino `class="content"`, aun no se en que parte o que template se debe cambiar. Apenas puedo busco en donde.

**Comment by rpalaciosg** [comment]
Cree un PR con una alternatia para corregir el error de este issue en #84.
