### ISSUE TITLE
Cambiar la forma de interpolar cadenas para compatibilidad desde Python 3.4 en `conf.py`

### ISSUE THREAD

**Issue by rpalaciosg** [PythonEcuador/PythonEcuador.github.io#81]
Intentando construir el proyecto local mente, y al tener instalado _python3.5_ y no la versión de _python3.6_ obtuve un error al ejecutar el comando ```$nikola build```.

https://github.com/PythonEcuador/PythonEcuador.github.io/blob/0e25d8f02e870424e51c601ac3e8962edbd239e5/conf.py#L28
 
Este error aparece por la linea a continuación del archivo `conf.py`, ya que usa la nueva forma para interpolar cadenas de _python3.6_.

![string_format_compatible_python_3 6_mas](https://user-images.githubusercontent.com/11642622/45593396-62701b00-b94b-11e8-8340-7da453576672.png)

Aunque esto se soluciona instalando la nueva versión de _3.6_,  solo es esta linea de código la que hace que el proyecto requiera versión _python3.6_.

@stsewd me propone la idea  de hacer `downgrade` es decir cambiar la forma de interpolar las cadenas en la línea del error en cuestión, reemplazando con otra forma que sea compatible con  python 3.4.+ en adelante.

por lo que propongo la siguiente forma:
```python
SITE_URL = 'https://{0}'.format(deploy_site)
```

**Comment by stsewd** [comment]
Si, esa es la mejor solución. siéntete libre de enviar el pull request con el cambio

**Comment by rpalaciosg** [comment]
listo, esta enviado el PR.

**Comment by stsewd** [comment]
Arreglado en https://github.com/PythonEcuador/PythonEcuador.github.io/pull/82
