### ISSUE TITLE
Agregar a Jet Brains a lista de sponsors

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#83]
Gracias Jet Brains por ayudar a la comunidad! Gracias a ellos tendremos licencias para sortear en cada meetup!

Debemos poner su logo https://www.jetbrains.com/company/press/#images-logos e indicar que nos ayudan con licencias (cada licencia dura un año) y stickers (pronto).

Dónde deberíamos ponerlos? en mención especial o en sponsors recurrentes?

**Comment by rpalaciosg** [comment]
wow, que bien. Esas noticias pueden atraer mas a la comunidad. 
Hablando de stickers, puse algunas alternativas para ayudar en el diseño del logo del PyPizza en #27 . Cuando puedan le den un vistazo. perdón por el spam en otro issue.
