### ISSUE TITLE
Mencionar que se debe linkear al issue que se resuelve cuando se crea un PR

### ISSUE THREAD

**Issue by stsewd** [PythonEcuador/PythonEcuador.github.io#87]
Esto debe ser actualizado en la guía de contribución, con algo así: Al crear un pull request en la descripción puedes enlazar al PR que estás resolviendo usando `close #n` donde , n es el número del issue. Por ejemplo para el issue número 20: `close #20`. GitHub creará un enlace automáticamente.

Explicar que esto es necesario para que sea más fácil ver si ya existe un PR abierto que arregla un issue, y que cuando el PR se mergea, el issue se cierra automáticamente.

---

Si estás interesad@ en hacer esta tarea, comentalo, así otras personas lo saben, tienes dudas? pregúntanos en telegram o en este issue.

**Comment by rpalaciosg** [comment]
puedo trabajar en esto?

**Comment by stsewd** [comment]
@rpalaciosg claro que si! pero tal vez te interesa tomar un issue más grande? como https://github.com/PythonEcuador/PythonEcuador.github.io/issues/29

**Comment by rpalaciosg** [comment]
@stsewd claro no hay problema voy a trabajar en #29 muchas gracias.
